apiVersion: v1
kind: Secret
metadata:
  name: db-creds-manifest
  namespace: test
immutable: false
type: Opaque
data:
  username: aml0ZW4K
  password: aml0ZW5AMTIzCg==
stringData:
  token: abcd1a2b3c4d5e6f # stringData no need to encode
  # username: jitenp if same key i used it is overwritten

# The data inside a file must be base64 encoded,when created using kubernetes manifest file.
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-consume
  namespace: test
  labels:
    app: nginx
spec:
  containers:

  - name: nginx
    image: nginx
  
 
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-creds-manifest
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-creds-manifest
          key: password

    ports:
    - name: web
      containerPort: 80

  

    

