kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-binding
  namespace: dev
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-service-binding
  namespace: dev
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: developer-service
  apiGroup: ""
